In [7]:
# multi dimensional numpy array
import numpy as np

In [11]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [89, 45, 17],
                         [66, 77, 88]])

In [12]:
print(climate_data)

[[ 73  67  43]
 [ 91  88  64]
 [ 87 134  58]
 [ 89  45  17]
 [ 66  77  88]]


In [13]:
climate_data.shape

(5, 3)

In [15]:
w1,w2,w3= 0.2,0.5,0.3

In [17]:
weights=np.array([w1,w2,w3])

In [18]:
weights

array([0.2, 0.5, 0.3])

In [19]:
weights.shape

(3,)

In [21]:
#3d array
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


In [22]:
arr3.shape

(2, 2, 3)

In [23]:
weights.dtype

dtype('float64')

In [24]:
climate_data.dtype

dtype('int64')

In [25]:
#3d array
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10.2,11.3,12.4]]])


In [26]:
arr3.dtype

dtype('float64')

In [27]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [ 89,  45,  17],
       [ 66,  77,  88]])

In [ ]:
# we use matmul function to perform matrix multiplication of two arrays. It is used to perform the dot product of two arrays. The matmul function is equivalent to the dot function, but it is more efficient for large arrays.

In [28]:
np.matmul(climate_data,weights)

array([ 61. ,  81.4, 101.8,  45.4,  78.1])

In [29]:
climate_data @ weights

array([ 61. ,  81.4, 101.8,  45.4,  78.1])

In [ ]:
#working with csv data files

In [32]:
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [33]:
climate_data

array([[ 19.98, 112.09,  78.4 ],
       [ 43.03,  99.87,  34.76],
       [ 34.28,  52.85,  47.73],
       ...,
       [ 42.87,  91.11,  21.56],
       [ 20.9 , 133.  ,  52.08],
       [ 13.69,  51.68,  40.59]], shape=(10000, 3))

In [35]:
climate_data.shape

(10000, 3)

In [36]:
yeilds = climate_data @ weights

In [37]:
yeilds

array([83.561, 68.969, 47.6  , ..., 60.597, 86.304, 40.755],
      shape=(10000,))

In [ ]:
#joining two arrays using concatenate function. It is used to join two or more arrays along a specified axis. The concatenate function takes a tuple of arrays as input and returns a new array that is the concatenation of the input arrays.
climate_data= np.concatenate((climate_data,yeilds.reshape(10000,1)),axis=1)

In [39]:
climate_data

array([[ 19.98 , 112.09 ,  78.4  ,  83.561],
       [ 43.03 ,  99.87 ,  34.76 ,  68.969],
       [ 34.28 ,  52.85 ,  47.73 ,  47.6  ],
       ...,
       [ 42.87 ,  91.11 ,  21.56 ,  60.597],
       [ 20.9  , 133.   ,  52.08 ,  86.304],
       [ 13.69 ,  51.68 ,  40.59 ,  40.755]], shape=(10000, 4))

In [40]:
np.savetxt('climate_results.txt',climate_data,fmt='%.2f',header='temperature,rainfall,humidity,yeilds_apples',comments='')

In [ ]:
#mathematics np.sum,np.exp,np.round
#array manipulation np.reshape,np.stack,np.concatenate,np.split
#linear algebra np.matmul,np.dot,np.transpose,np,eigvals
#statistics np.mean,np.median,np.std,np.var