In [ ]:
# numpy is library for numerical computing in python

In [ ]:
kanto_temp= 73
kanto_rainfall=67
kanto_humidity= 80


In [5]:
w1,w2,w3= 0.2,0.5,0.3

In [6]:
kanto_yeild_apples = kanto_temp*w1 + kanto_rainfall*w2 + kanto_humidity*w3 
kanto_yeild_apples 

72.1

In [7]:
kanto=[73,67,80]
johto=[75,65,70]
hoenn=[80,70,60]
sinnoh=[60,80,90]
unova=[70,75,80]

In [8]:
weights =[w1,w2,w3]

In [9]:
def crop_yeild(region,weights):
    result=0
    for x, w in zip(region,weights):
        result+= x*w
    return result

In [10]:
crop_yeild(kanto,weights)

72.1

In [11]:
crop_yeild(johto,weights)

68.5

In [17]:
for x,y in zip(kanto,weights):
    print(x*y)

14.600000000000001
33.5
24.0


In [19]:
import numpy as np

In [20]:
kanto = np.array(kanto)

In [21]:
kanto

array([73, 67, 80])

In [22]:
weights = np.array(weights)

In [23]:
type(kanto)

numpy.ndarray

In [24]:
type(weights)

numpy.ndarray

In [25]:
weights[0]

np.float64(0.2)

In [26]:
kanto[2]

np.int64(80)

In [ ]:
# operating on numpy array is very easy and fast as compared to list

In [27]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(a, b, out=None)
    dot(a, b, out=None)

    Dot product of two arrays. Specifically,

    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).

    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.

    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.

    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.

    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::

        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

    It uses an optimized BLAS library when possible (see `numpy.linalg`).

    Parameters
    ----------
    a : array_like


In [28]:
np.dot(kanto,weights)

np.float64(72.1)

In [29]:
kanto*weights

array([14.6, 33.5, 24. ])

In [30]:
(kanto*weights).sum()

np.float64(72.1)

In [31]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [32]:
arr1*arr2

array([ 4, 10, 18])

In [34]:
arr2.sum()

np.int64(15)

In [ ]:
#benefits of using numpy over list is that it is very fast and easy to use. It has many built in functions which makes it easy to use. It is also very efficient in terms of memory usage. It is also very easy to use with other libraries like pandas, matplotlib, etc. It is also very easy to use with other languages like C, C++, etc. It is also very easy to use with other platforms like Jupyter Notebook, Google Colab, etc.

In [35]:
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [36]:
%%time 
result=0
for x,y in zip(arr1,arr2):
    result+=x*y
result


CPU times: total: 250 ms
Wall time: 249 ms


833332333333500000

In [37]:
%%time
result_np = np.dot(arr1_np,arr2_np)
result_np

CPU times: total: 0 ns
Wall time: 2 ms


np.int64(833332333333500000)